apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: rakshith3/hello-world-python:latest
        ports:
        - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  type: NodePort                   # Changed from LoadBalancer to NodePort
  selector:
    app: hello-python
  ports:
    - protocol: TCP
      port: 5005                  # Service port inside cluster
      targetPort: 5005            # Container port
      nodePort: 30005             # External port on your minikube VM
